### ISSUE TITLE
Automatically download the DNN packages for the user

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/DNNQuickSite#10]
This is a proposed enhancement for a future version.  

Current user experience if I don't already have the package I want to use:
- Open app
- Choose DNN version
- Click to go to the site
- Manually download that DNN version
- Remember where I saved it
- Go back to the app
- Browse for and (hopefully) find the downloaded DNN package
- Continue to the next step

Proposed User Experience:
- Open app
- Choose the DNN version
- Click next
- The app looks for and downloads the DNN package
- Continue on the next step

Just to be clear, this is one of two options on the first step.  The second option should remain for those that aren't connected to the internet, or those that are installing modified/local packages.  For example, I install a package all of the time in MakeDNNSite that has modules that install when DNN installs.

**Comment by nvisionative** [comment]
@hismightiness Currently the way it works, the user selects the desired DNN version in the drop down list.  Then, when they click the button to the right of the drop down list, the user is prompted for a location to save the package.  Are you hoping for a different experience?  If so, can you describe?  Thanks!

**Comment by hismightiness** [comment]
I updated the original post.

**Comment by nvisionative** [comment]
Thank you for clarifying - it makes sense now.
