### ISSUE TITLE
Error when using hyphens in DB name

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/DNNQuickSite#19]
In the DB step, I used a hyphen for my database name:

![2016-02-26_0018](https://cloud.githubusercontent.com/assets/938023/13346888/7f895e20-dc1e-11e5-9e02-8d61b7d022c7.png)

This error occured:

![2016-02-26_0013](https://cloud.githubusercontent.com/assets/938023/13346843/30ad1ce2-dc1e-11e5-95f1-1873a8251e5a.png)

The progress bar still continued as if something was happening, but the DB wasn't created.

**Comment by nvisionative** [comment]
Thanks  - we'll look into this.
