### ISSUE TITLE
Site Info > Site Location doesn't remember the last location (kind of)

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/DNNQuickSite#21]
When you install a site after having done it at least once before, I expect for the last install location to be remembered, so I don't have to navigate to it all over again.  

When I get to this step, the textbox is empty, and when I click to browse for the location again, it's selected, but I can't really tell that it's selected, until I click on it again (after scrolling to find it).

![2016-02-26_0022](https://cloud.githubusercontent.com/assets/938023/13347016/84ff80e0-dc1f-11e5-8a5b-3c5d5cdf42ae.png)

**Comment by nvisionative** [comment]
This is a inherent problem with the folderBrowserDialog control.  We have coded using a 3rd party control and it works great.  However, it created another issue that we are trying to solve.  Will keep you posted.
