### ISSUE TITLE
Reinstalling same site does not respect the selected certificate

### ISSUE THREAD

**Issue by valadas** [nvisionative/DNNQuickSite#370]
Not a big deal but a small glitch...

Steps to reproduce
1. Install a site using SSL and pick `certificateA`
2. Run the site and everything is setup fine, very nice
3. Later on, use nvQuickSite again to replace that site but pick `certificateB` instead

Expected behavior:
The replaced site should now be using `certificateB`

What is wrong:
The replaced site still uses `certificateA`

**Comment by david-poindexter** [comment]
@valadas thanks for reporting this.  I have a PR ready for your review if you want to pull, build, and test to see if this fix worked.
